// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZh1GjKGgVd1ni0S3aqmwlXLJWbhiG0c',
    appId: '1:323761786783:web:96b034173338348ac9f7aa',
    messagingSenderId: '323761786783',
    projectId: 'birds-477e7',
    authDomain: 'birds-477e7.firebaseapp.com',
    storageBucket: 'birds-477e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGhh3JM8Ed79MxdUtSkYGcN9-3NS1yfbs',
    appId: '1:323761786783:android:8d26dcf741d666d8c9f7aa',
    messagingSenderId: '323761786783',
    projectId: 'birds-477e7',
    storageBucket: 'birds-477e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtKp_QL5bU2JK1pEsBaHq2ZlMUGEOP7b8',
    appId: '1:323761786783:ios:47cd3dd8904185ecc9f7aa',
    messagingSenderId: '323761786783',
    projectId: 'birds-477e7',
    storageBucket: 'birds-477e7.appspot.com',
    iosBundleId: 'com.example.wingspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZh1GjKGgVd1ni0S3aqmwlXLJWbhiG0c',
    appId: '1:323761786783:web:16278db579519b08c9f7aa',
    messagingSenderId: '323761786783',
    projectId: 'birds-477e7',
    authDomain: 'birds-477e7.firebaseapp.com',
    storageBucket: 'birds-477e7.appspot.com',
  );
}
